services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: driver_attendance
    restart: unless-stopped
    working_dir: /var/www
    command: php-fpm
    ports:
      - "9000:9000"
    volumes:
      - /var/www/driver-attendance:/var/www
    networks:
      - laravel

networks:
  laravel:
