version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: driver_attendance
    restart: unless-stopped
    working_dir: /var/www/html
    command: php-fpm
    volumes:
      - .:/var/www/html
      - laravel_storage:/var/www/html/storage
      - laravel_bootstrap:/var/www/html/bootstrap/cache
    networks:
      - laravel

networks:
  laravel:

volumes:
  laravel_storage:
  laravel_bootstrap:

ports:
  - "9000:9000"
